routes/web.php
<?php
use Illuminate\Support\Facades\Artisan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('localization/{locale}','LocalizationController@index');
Route::get('/', 'HomeController@home');
//for contact us
Route::get('/contactus','HomeController@contact')->name('contactus');
Route::get('/aboutus','HomeController@aboutus');

//for event list
Route::get('eventlist','HomeController@EventList');

// Event detail
Route::get('eventDetail/{id}', 'HomeController@eventDetail')->name('event-detail');
Route::any('/eventsearch','HomeController@eventSearch')->name('eventsearch');


Route::get('insert_event',function(){
    $e=Artisan::call('add:event');
    //1 return true 0 return false
    if($e==0)
    {
        return response("insert successfully", 200);
    }
    else
    {
        return response("Not insert", 200);
    }
});

//for login , Registration and Logout
Auth::routes();
Auth::routes(['verify' => true]);

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/mail_demo', 'HomeController@mail_demo')->name('mail_demo');

Route::group(['middleware'=>['verified','auth']],function(){

    Route::group(['middleware'=>['checkPayUMoneyKey']],function(){
        //for event CRUD
        Route::resource('events', 'EventsController');
        Route::get('/events/delete/{event}', 'EventsController@destroy')->name('events.destroy');

        //to get only Trashed/Deleted Record of event
        Route::get('trashed_events','EventsController@trashed_event')->name('events.trashed_events');
       
        //to restore the softdeleted event record
        Route::get('restore_events/{id}','EventsController@restore_event')->name('events.restore_events');
       
        //to forcedelete event record
        Route::get('forcedelete_events/{id}','EventsController@forcedel_event')->name('events.forcedelete_events');


        //for package CRUD
        Route::resource('packages', 'PackagesController');
        Route::get('/packages/delete/{package}', 'PackagesController@destroy')->name('packages.destroy');
       
        //to get only Trashed/Deleted Record of package
        Route::get('trashed_packages','PackagesController@trashed_pkg')->name('packages.trashed_packages');
       
        //to restore the softdeleted package record
        Route::get('restore_packages/{id}','PackagesController@restore_pkg')->name('packages.restore_packages');
       
        //to forcedelete package record
        Route::get('forcedelete_packages/{id}','PackagesController@forcedel_pkg')->name('packages.forcedelete_packages');
       
        //for package feature CRUD
        Route::resource('package_features', 'PackageFeaturesController');
        Route::get('/package_features/delete/{package_features}', 'PackageFeaturesController@destroy')->name('package_features.destroy');

        //to get only Trashed/Deleted Record of package feature
        Route::get('trashed_packagefeatures','PackageFeaturesController@trashed_PackageFeatures')->name('package_features.trashed_PackageFeatures');
    
        //to restore the softdeleted package feature record
        Route::get('restore_packagefeatures/{id}','PackageFeaturesController@restore_PackageFeatures')->name('package_features.restore_PackageFeatures');
    
        //to forcedelete package feature record
        Route::get('forcedelete_packagefeatures/{id}','PackageFeaturesController@forcedel_PackageFeatures')->name('package_features.forcedelete_PackageFeatures');
 
    });

    // for profile update
    Route::get('/profileedit','ProfileEditController@index')->name('profile-edit');
    Route::post('/profileedit-update','ProfileEditController@update')->name('profile-edit-post');

    // add PayUMoney Key
    Route::match(['get','post'],'payumoney_key', 'ProfileEditController@add_payumoney_key')->name('payumoney-key');

    // change password
    Route::get('/changepassword','ChangePwdController@index')->name('change-pwd');
    Route::post('/pwd-change-post','ChangePwdController@change');
        
    // Event detail
    Route::post('eventDetail/{id}', 'HomeController@eventDetail')->name('event-detail');

    // for booking
    Route::get('booking/{id}','HomeController@booking');
    Route::post('booking/{id}','HomeController@booking');
    Route::get('booking/cancel/{id}','HomeController@booking_cancel');
    Route::get('mybookings','HomeController@myBookings')->name('my-bookings');
    Route::get('invoice/{id}','HomeController@invoice')->name('invoice');

    // payumoney gateway
    Route::get('payment/{uid}/{pkg_book_id}', 'PayUMoneyController@index')->name('payment');
    Route::any('payment/status', 'PayUMoneyController@status')->name('payment-status');

    // notifications
    Route::get('get_notification/{id}','HomeController@get_notification')->name('get-notification');
    Route::match(['get', 'post'],'notification_details/{id}','HomeController@notification_details')->name('notification-details');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    // internaally call by laravel and import from MustVerifyEmail Class 
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fname','lname','email','password','dob','address','city','state','country','contact_no','profile','payumoney_key', 'payumoney_salt',
    ];
    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    // this array field is not display when we fetch data/print
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    public function getFullNameAttribute() {
        return $this->fname . ' ' . $this->lname;
    }
    
    public function events()
    {
        return $this->hasMany('App\models\Events','uid');
    }

    public function packages()
    {
        return $this->hasMany('App\models\Packages','uid');
    }
    
    public function package_features()
    {
        return $this->hasMany('App\models\PackageFeatures','uid');
    }

    public function review()
    {
        return $this->hasMany('App\models\Review','uid');
    }

    public function pkg_bookings()
    {
        return $this->hasMany('App\models\Booking','uid');
    }

    public function payments()
    {
        return $this->hasMany('App\models\Payment','uid');
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\models\Packages;
use App\models\Events;
use App\models\Review;
use App\models\Booking;
use App\models\MyNotification;
use App\models\Payment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

use Mail;
// use App\Mail\VerificationMail;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        // $packages = Packages::all();
        return view("home");
    }

    public function home()
    {
        $packages = Packages::with('events')->whereRaw('registration_end_date >= curdate()')->limit(3)->orderBy('price_per_person','DESC')->orderBy('registration_end_date', 'ASC')->get();
        //dd($packages);
        $images = Packages::get();
        $reviews = Review::all();
        $total_events = Events::all()->count();
        $total_payments = Payment::all()->count();
        $total_users = User::all()->count();
        $total_packages = Packages::all()->count();
        return view("home/index",compact('packages','reviews','images','total_users','total_packages','total_events','total_payments'));
    }

    public function mail_demo(){
        $data = array();
        $user = User::find(9);
        // Mail::to($user['email'])->send(new VerificationMail($user));

        $data['user'] = $user;
        $data['token'] = \Illuminate\Support\Str::uuid();
        Mail::send('mail.demo', $data, function($message) {
            $message->to('vaghelajanak97@gmail.com', 'Janak Vaghela')
                    ->subject('Test');
        });
 
        if (Mail::failures())
           return 'Sorry! Please try again later';
        else
           return 'Great! Successfully send in your mail';
    }

    public function EventList()
    {
        $packages = Packages::with('events')->whereRaw('registration_end_date >= curdate()')->orderBy('price_per_person','DESC')->orderBy('registration_end_date', 'ASC')->paginate(4);
        return view("home/event_list",compact('packages'));
    }

    public function eventDetail(Request $request,$id)
    {
        if($request->get('reviewsubmit'))
        {
            // review can only give by paid user
            // $booked = Booking::where('payment_status','=',1)->where('pid','=',$id)->where('uid','=', Auth::user()->id)->count();
            
            // review can only give by user who booked package
            $booked = Booking::where('pid','=',$id)->where('uid','=', Auth::user()->id)->count();
            if($booked > 0){
                $review = new Review();
                $review->uid = Auth::user()->id;
                $review->pid = $id;
                $review->rating = $request->get('rating');
                $review->review = $request->get('review');
                $review->save();
            }else{
                $msg = "You can not give review until you book it...!";
            }
        }

        $reviews = Review::where('pid','=',$id)->with('users')->orderBy('rating','DESC')->get();
        $pkg_details  = Packages::with('users')->find($id);
        $features = $pkg_details->package_features;
        
        return view("home/view_eventDetail",compact('pkg_details','reviews','features', 'msg'));
    }

    //for search
    public function eventSearch(Request $request)
    {
        //it will return value which we search
        if($request->has('search')){
            if($request->get('search_type') == "1"){
                $packages = Packages::whereRaw('registration_end_date >= curdate()')->whereHas('events', function ($query) use ($request) {
                    $query->where('event_name', 'like', "%{$request->get('search')}%");
                })->paginate(2);
            }elseif($request->get('search_type') == "2"){
                $packages = Packages::search($request->get('search'),null,true)->whereRaw('registration_end_date >= curdate()')->paginate(2);
            }
        }else{
            $packages = Packages::paginate(2);
        }
        return view("home/event_list", compact('packages'));
    }

    public function contact(Request $request)
    {
        return view("home/contact_us"); 
    }

    public function aboutus(Request $request)
    {
        $total_events = Events::all()->count();
        $total_payments = Payment::all()->count();
        $total_users = User::all()->count();
        $total_packages = Packages::all()->count();
        return view("home/about_us",compact('total_users','total_packages','total_events','total_payments')); 
    }

    public function booking(Request $request,$id)
    {
        $package =  Packages::find($id);
        if($request->get('btn_sub'))
        {
            $user = Auth::user();
            if($package->available_seat >= $request->get('totalper')){
                $booking = new Booking();
                $booking->uid = $user->id;
                $booking->pid = $id;
                $booking->total_persons = $request->get('totalper');
                $totalamt=$request->get('totalper')*$request->get('price_per_person');
                $booking->total_amount = $totalamt;
                $booking->deposite = $request->get('deposite')*$request->get('totalper');
                if($package->type == "public")
                    $booking->status = 1;
                $booking->save();

                $notify = new MyNotification();
                $notify->from_uid = $user->id;
                $notify->to_uid = $package->uid;
                $notify->pkg_book_id = $booking->id;
                $notify->msg = $package->pkg_name ." was booked by ". $user->full_name;
                $notify->save();
                return redirect("/mybookings");
            }else{
                return back()->with('msg', $request->get('totalper').' seats are not available...!')->withInput();
            }
        }
        return view("home/booking",compact('package'));
    }
 
    public function booking_cancel(Request $request, $id)
    {
        $booking =  Booking::with('packages')->find($id);
        $booking->status = 3;
        $booking->save();

        $notify = new MyNotification();
        $notify->from_uid = Auth::user()->id;
        $notify->to_uid = $booking->packages->uid;
        $notify->pkg_book_id = $id;
        $notify->msg = $booking->packages->pkg_name ." was canceled by ". Auth::user()->full_name;
        $notify->save();
        return redirect("/mybookings");
    }
 
    public function myBookings(Request $request)
    {
        $all_booking = Booking::where('uid','=',Auth::user()->id)->with('users')->orderBy('created_at','Desc')->get();
        return view("home/my_bookings",compact('all_booking'));
    }
    
    public function invoice(Request $request, $id)
    {
        $booking = Booking::find($id);
        $user = User::find($booking->uid);
        $pkg = Packages::find($booking->pid);
        $payment = Payment::where('pkg_book_id', '=', $booking->id)->first();
        return view("home/invoice",compact('booking','user', 'pkg', 'payment'));
    }
    
    public function get_notification(Request $request, $id){
        $notifications = MyNotification::where('to_uid', '=', $id)->orderBy('created_at', 'desc')->get();
        return $notifications->toJson();
    }

    public function notification_details(Request $request, $id){
        $notification = MyNotification::with('pkg_booking')->with('from_user')->find($id);
        $package = Packages::find($notification->pkg_booking->pid);
        if($notification->read_status == 0){
            $notification->read_status = 1;
            $notification->save();
        }

        if($package->uid != Auth::user()->id)
            return redirect("/mybookings");

        if($request->get('btn_submit'))
        {
            $pkg_booked = Booking::find($notification->pkg_booking->id);
            $pkg_booked->status = $request->get('btn_submit');
            $pkg_booked->save();
            $notification->pkg_booking->status = $request->get('btn_submit');

            $notify = new MyNotification();
            $notify->from_uid = $notification->to_uid;
            $notify->to_uid = $notification->from_uid;
            $notify->pkg_book_id = $notification->pkg_book_id;
            $status = "";
            if ($request->get('btn_submit') == 1)
                $status = "accepted";
            else
                $status = "denied";
            $notify->msg = $package->pkg_name ." was " . $status;
            $notify->save();
        }

        return view("home/notification_details", compact('notification', 'package'));
    }
    
}

resources/views/home/add_event.blade.php
@extends('home.header')

@section('main-content')
<section class="agenda-section text-center" >
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>    
            <div class="col-md-8">
                <div class="card">
                    <h1>{{ $task }} Event</h1>
                    {{-- <div class="card-header" style="font-size:30px;text-align:center">{{ __('Register') }}</div> --}}
                    <form method="POST" action="{{ $submit_route }}" enctype="multipart/form-data">
                        @csrf
                        @if ($task == 'Edit')
                            @method('PUT')
                        @endif
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Event Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" placeholder="Enter Event Name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{old('name', @$event->event_name)}}" pattern="[a-zA-Z0-9 ]+" maxlength="50" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div><br>
                        <div class="form-group row mb-0">
                            <div class="col-md-12 offset-md-4">
                                <input type="reset" class="btn btn-primary" value="Reset" name="reset" />
                                <input type="submit" name="btn_sub" class="btn btn-primary" value="Submit" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/home/view_event.blade.php
@extends('home.header')

@section('main-content')
<section class="agenda-section text-center" >
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>    
            <div class="col-md-8">
                <div class="card">
                    @if (session()->get('msg'))
                        <p class="alert alert-success">{{ session()->get('msg') }}</p>
                    @endif
                    <h1>View Events</h1>
                    <a class="btn btn-info" href="{{ route('events.create') }}">Add Event</a>
                    <a class="btn btn-info" href="{{ route('events.trashed_events') }}">View Trash</a>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="text-center" scope="col">Id</th>
                                <th class="text-center" scope="col">Name</th>
                                <th class="text-center" scope="col" colspan="2">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @isset($events)
                            @foreach ($events as $row)
                                <tr>
                                    <td scope="row">{{ $loop->iteration }}</td>
                                    <td>{{ $row->event_name }}</td>
                                    <td><a class="btn btn-primary" href="{{ route('events.edit', $row->id) }}">Edit</a>
                                        <a class="btn btn-danger" href="{{ route('events.destroy', $row->id) }}">Delete</a></td>
                                </tr>
                            @endforeach
                            @endisset
                            @isset($trashed_events)
                            @foreach ($trashed_events as $row)
                                <tr>
                                    <td scope="row">{{ $loop->iteration }}</td>
                                    <td>{{ $row->event_name }}</td>
                                    <td><a class="btn btn-primary" href="{{ route('events.restore_events', $row->id) }}">Restore</a>
                                        <a class="btn btn-danger" href="{{ route('events.forcedelete_events', $row->id) }}">Force Delete</a>
                                </tr>
                            @endforeach
                            @endisset

                        </tbody>
                    </table>
                    @isset($events)
                            <div style="">
                                {{ $events->links() }} 
                            </div>
                    @endisset
                    @isset($trashed_events)
                            <div style="">
                                {{ $trashed_events->links() }} 
                            </div>
                    @endisset
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/home/view_package.blade.php
@extends('home.header')

@section('main-content')
<section class="agenda-section" >
    <div class="container">
        <div class="row">    
            <div class="col-md-12">
                <div class="card">
                    <div class="text-center">
                    @if (session()->get('msg'))
                        <p class="alert alert-success">{{ session()->get('msg') }}</p>
                    @endif
                    <h1>View Packages</h1>
                    <a class="btn btn-info" href="{{ route('packages.create') }}">Add Package</a>
                    <a class="btn btn-info" href="{{ route('packages.trashed_packages') }}">View Trash</a>
                    </div>
                    @isset($packages)
                    @foreach ($packages as $row)
                    <div class="col-lg-12 guide-all-list">
                        <!-- Work Item -->
                        <div class="col-lg-4 col-sm-6 col-xs-12">
                            <div class="guide-item-img">
                                <div class="guide-item">
                                    <img src="{{ URL::to('home_res/images/package/'.$row->image) }}">
                                </div>
                            </div>
                        </div>
                        <!--/ End: Work Item -->
                        <!-- Work Item -->
                        <div class="col-lg-8 col-sm-6 col-xs-12">
                            <div class="guide-item">
                                <div id="socialHolder">
                                    <div id="socialShare" class="btn-group share-group">
                                        <a data-toggle="dropdown" class="btn btn-info">
                                                <i class="fa fa-share-alt fa-inverse"></i>
                                        </a>
                                        <ul class="dropdown-menu" style="min-width: 0px;padding: 0px;background-color: transparent;">
                                            <li>
                                                <a target="blank" title="WhatsApp" data-action="share/whatsapp/share" href="https://api.whatsapp.com/send?text={{ url('/') }}/eventDetail/{{$row->id}}%0A%0A I inviting you for {{$row->pkg_name}}.%0A%0A Click above link to check package information." class="btn btn-whatsapp">
                                                    <i class="fa fa-whatsapp"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a title="Email" class="btn btn-mail" target="blank" href="mailto:?subject=Invitation&body={{ url('/') }}/eventDetail/{{$row->id}}%0A%0A I inviting you for {{$row->pkg_name}}.%0A%0A Click above link to check package information.">
                                                    <i class="fa fa-envelope"></i>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <h3 class="title">{{$row->pkg_name}}
                                    {{-- {{$row->eid}} --}}
                                    {{-- {{$event->event_name}} --}}
                                </h3>
                                <h4>{{$row->events->event_name}}</h4>
                                <h4 class="title">Type:{{$row->type}}</h4>
                                <!-- /.title -->
                                <h4>Deposite Per Person - {{$row->deposite_per_person}}</h4>
                                <h4>Available Seat - {{$row->available_seat}}</h4>
                                <!-- /.description -->
                                <div class="post-meta">
                                    <ul>
                                        <li>
                                            <span>Price Per Person -</span>
                                            {{$row->price_per_person}}
                                        </li>
                                        <li><i class="fa fa-clock-o"></i> <span>Person Capacity - {{$row->person_capacity}}</span>
                                        </li>
                                        <li><i class="fa fa-map-marker"></i> <span>City - {{$row->city}}</span>
                                        </li>
                                    </ul>
                                </div>
                                <a href="eventDetail/{{$row->id}}" class="btn btn-chos hvr-shutter-in-horizontal" title="read">read more</a>
                                <div style="text-align: right">
                                    <h4><a class="btn btn-primary" href="{{ route('packages.edit', $row->id) }}">Edit</a>
                                        <a class="btn btn-danger" href="{{ route('packages.destroy', $row->id) }}">Delete</a>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div> 
                    @endforeach
                    @endisset
                    @isset($trashed_packages)
                    @foreach ($trashed_packages as $row)
                    <div class="col-lg-12 guide-all-list">
                        <!-- Work Item -->
                        <div class="col-lg-4 col-sm-6 col-xs-12">
                            <div class="guide-item-img">
                                <div class="guide-item"><img alt="" class=""
                                        src="{{ URL::to('home_res/images/package/'.$row->image) }}">
                                </div>
                            </div>
                        </div>
                        <!--/ End: Work Item -->
                        <!-- Work Item -->
                        <div class="col-lg-8 col-sm-6 col-xs-12">
                            <div class="guide-item">
                                <h3 class="title">{{$row->pkg_name}}
                                    {{-- {{$row->eid}} --}}
                                    {{-- {{$event->event_name}} --}}
                                </h3>
                                <h4>{{$row->events->event_name}}</h4>
                                <h4 class="title">Type:{{$row->type}}</h4>
                                <!-- /.title -->
                                <h4>Deposite Per Person - {{$row->deposite_per_person}}</h4>
                                <!-- /.description -->
                                <div class="post-meta">
                                    <ul>
                                        <li>
                                            <span>Price Per Person -</span>
                                            {{$row->price_per_person}}
                                        </li>
                                        <li><i class="fa fa-clock-o"></i> <span>Person Capacity - {{$row->person_capacity}}</span>
                                        </li>
                                        <li><i class="fa fa-map-marker"></i> <span>City - {{$row->city}}</span>
                                        </li>
                                    </ul>
                                </div>
                                <a href="eventDetail/{{$row->id}}" class="btn btn-chos hvr-shutter-in-horizontal" title="read">read more</a>
                                <div style="text-align: right">
                                    <h4><a class="btn btn-primary" href="{{ route('packages.restore_packages', $row->id) }}">Restore</a>
                                        <a class="btn btn-danger" href="{{ route('packages.forcedelete_packages', $row->id) }}">Force Delete</a>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div> 
                    @endforeach
                    @endisset
                    {{-- <div style="">
                            {{ $packages->appends(['search_type' =>  Request::get('search_type'),'search' => Request::get('search') ])->links() }} 
                    </div> --}}

                    @isset($packages)
                    <div style="">
                        {{ $packages->links() }} 
                    </div>
                    @endisset
                    @isset($trashed_packages)
                    <div style="">
                        {{ $trashed_packages->links() }} 
                    </div>
                    @endisset

                    {{-- <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="text-center" scope="col">Id</th>
                                <th class="text-center" scope="col">Type</th>
                                <th class="text-center" scope="col">City</th>
                                <th class="text-center" scope="col">Contact No</th>
                                <th class="text-center" scope="col">Price Per Person</th>
                                <th class="text-center" scope="col">Deposite Per Person</th>
                                <th class="text-center" scope="col">Person Capacity</th>
                                <th class="text-center" scope="col" colspan="2">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($packages as $row)
                                <tr>
                                    <td scope="row">{{ $row->id }}</td>
                                    <td>{{ $row->type }}</td>
                                    <td>{{ $row->city }}</td>
                                    <td>{{ $row->contact_no }}</td>
                                    <td>{{ $row->price_per_person }}</td>
                                    <td>{{ $row->deposite_per_person }}</td>
                                    <td>{{ $row->person_capacity }}</td>
                                    <td><a class="btn btn-primary" href="{{ route('packages.edit', $row->id) }}">Edit</a>
                                        <a class="btn btn-danger" href="{{ route('packages.destroy', $row->id) }}">Delete</a></td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table> --}}
                </div>
            </div>
        </div>
    </div>
</section>
@endsection